name: Pylint Badge

on:
  push:
    paths:
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devs-des1re/pylint-ghpages-action@v1
        with:
          path: "."
